[package]
name = "glommio"
version = "0.3.1"
authors = [ "Glauber Costa <glauber@datadoghq.com>",
            "Hippolyte Barraud <hippolyte.barraud@datadoghq.com>",
            "DataDog"]
edition = "2018"
description = "A set of utilities to allow one to write thread per core applications"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/DataDog/glommio"
homepage = "https://github.com/DataDog/glommio"
keywords = ["uring", "reactor", "thread-per-core"]
categories = ["asynchronous", "os", "filesystem", "network-programming"]
readme = "../README.md"

[features]
xdp = ["libbpf-sys", "bitflags"]
bench = []

[dependencies]
log = "0.4"
concurrent-queue = "1.1.2"
futures-lite = "1.11.1"
libc = "0.2.77"
socket2 = { version = "0.3.18", features = ["unix", "reuseport"] }
nix = "0.19.0"
bitmaps = "2.1.0"
typenum = "1.12"
scoped-tls = "1.0.0"
rlimit = "0.3.0"
lazy_static = "1.4.0"
enclose = "1.1.8"
scopeguard = "1.1.0"
pin-project-lite = "0.1.10"
smallvec = "1.4.2"
buddy-alloc = "0.4.1"
ahash = "0.5.7"
intrusive-collections = "0.9.0"
thiserror = "1.0"
libbpf-sys = { version = "0.1.0-1", optional = true }
bitflags = { version = "1.2.1", optional = true }
membarrier = "0.2.2"

[dev-dependencies]
futures = "0.3.5"
fastrand = "1.4.0"
tokio = { version = "0.3.5", default-features = false, features = ["rt", "macros", "rt-multi-thread", "net", "io-util", "time"] }
etherparse = "0.9.0"

[build-dependencies]
cc = "1.0.47"

[[bench]]
name = "executor"
harness = false

[[bench]]
name = "semaphore"
harness = false

[[bench]]
name = "local_channel"
harness = false

[[bench]]
name = "shared_channel"
harness = false

[[bench]]
name = "preempt"
harness = false

[[bench]]
name = "tcp"
harness = false

[[bench]]
name = "tokio_tcp"
harness = false

[[bench]]
name = "udp"
harness = false

[[bench]]
name = "nop"
harness = false
required-features = ["bench"]

[[bench]]
name = "sharding"
harness = false
